version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin # Set your desired admin username here
      - KEYCLOAK_ADMIN_PASSWORD=admin # Set your desired admin password here
      - DB_VENDOR= POSTGRES
      - DB_ADDR= postgres
      - DB_DATABASE= keycloak
      - DB_USER= keycloak
      - DB_SCHEMA= public
      - DB_PASSWORD= password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: start-dev
